version: '3'

volumes:
  {{ cookiecutter.project_slug }}_local_postgres_data: {}
  {{ cookiecutter.project_slug }}_local_postgres_data_backups: {}
  {{ cookiecutter.project_slug }}_local_solr-core-config: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    container_name: {{ cookiecutter.project_slug }}_local_django
    depends_on:
      - postgres
      {%- if cookiecutter.use_celery == 'y' %}
      - redis
      {%- endif %}
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    volumes:
      - .:/app:z
      - {{ cookiecutter.project_slug }}_local_solr-core-config:/app/config/solr-configset
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    container_name: {{ cookiecutter.project_slug }}_local_postgres
    volumes:
      - {{ cookiecutter.project_slug }}_local_postgres_data:/var/lib/postgresql/data
      - {{ cookiecutter.project_slug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: {{ cookiecutter.project_slug }}_local_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
      PGADMIN_CONFIG_LOGIN_BANNER: "'PGAdmin de dev !!'"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    depends_on:
      - postgres
    ports:
      - "8888:80"

  # à activer une fois solr schema généré
  # solr:
  #   image: solr:9
  #   container_name: {{ cookiecutter.project_slug }}_local_solr
  #   ports:
  #     - "8983:8983"
  #   restart: always
  #   # environment:
  #   #   SOLR_JAVA_MEM: "-Xms4g -Xmx4g"
  #   #   SOLR_OPTS: "-XX:-UseLargePages"
  #   volumes:
  #     - {{ cookiecutter.project_slug }}_local_solr-core-config:/opt/solr/server/solr/configsets/solr-configset:ro
  #   command:
  #     - solr-precreate
  #     - {{ cookiecutter.project_slug }}-index
  #     - /opt/solr/server/solr/configsets/solr-configset

  docs:
    image: {{ cookiecutter.project_slug }}_local_docs
    container_name: {{ cookiecutter.project_slug }}_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./{{ cookiecutter.project_slug }}:/app/{{ cookiecutter.project_slug }}:z
    ports:
      - '9000:9000'
    command: /start-docs
  {%- if cookiecutter.use_mailpit == 'y' %}

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: {{ cookiecutter.project_slug }}_local_mailpit
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if cookiecutter.use_celery == 'y' %}

  redis:
    image: docker.io/redis:6
    container_name: {{ cookiecutter.project_slug }}_local_redis

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celeryworker
    container_name: {{ cookiecutter.project_slug }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celerybeat
    container_name: {{ cookiecutter.project_slug }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_flower
    container_name: {{ cookiecutter.project_slug }}_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  {%- endif %}
  {%- if cookiecutter.frontend_pipeline in ['Gulp', 'Webpack'] %}

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_node
    container_name: {{ cookiecutter.project_slug }}_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      {%- if cookiecutter.frontend_pipeline == 'Gulp' %}
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
      {%- endif %}

  {%- endif %}
